# #############################################################################
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---

centralidp:
  enabled: true
  keycloak:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "centralidp.tx.test"
      annotations:
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://centralidp.tx.test"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
        nginx.ingress.kubernetes.io/use-regex: "true"
      tls: false
    # -- uncomment the following for persistance
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

managed-identity-wallet:
  enabled: true
  seeding:
    enabled: true
  miw:
    keycloak:
      url: "http://centralidp.tx.test/auth"
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  ingress:
    enabled: true
    hosts:
      - host: "managed-identity-wallets.tx.test"
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/cors-allow-origin: http://portal.tx.test
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
  # -- uncomment the following for persistance
  # postgresql:
  #   primary:
  #     persistence:
  #       enabled: true

dataconsumerOne:
  enabled: true
  secrets:
    edc-miw-keycloak-secret: UbfW4CR1xH4OskkovqJ2JzcwnQIrG7oj
  tractusx-connector:
    participant:
      id: BPNL00000003AZQP
    controlplane:
      ssi:
        miw:
          url: http://managed-identity-wallets.tx.test
          authorityId: BPNL00000003CRHK
        oauth:
          tokenurl: http://centralidp.tx.test/auth/realms/CX-Central/protocol/openid-connect/token
          client:
            id: satest01
      endpoints:
        management:
          authKey: TEST1
      ingresses:
        - enabled: true
          hostname: "dataconsumer-1-controlplane.tx.test"
          endpoints:
            - default
            - protocol
            - management
          tls:
            enabled: false
    dataplane:
      ingresses:
        - enabled: true
          hostname: "dataconsumer-1-dataplane.tx.test"
          endpoints:
            - default
            - public
          tls:
            enabled: false
    # -- uncomment the following for persistance
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

tx-data-provider:
  seedTestdata: true
  enabled: true
  secrets:
    edc-miw-keycloak-secret: pyFUZP2L9UCSVJUScHcN3ZEgy2PGyEpg
  tractusx-connector:
    participant:
      id: BPNL00000003AYRE
    controlplane:
      ssi:
        miw:
          url: http://managed-identity-wallets.tx.test
          authorityId: BPNL00000003CRHK
        oauth:
          tokenurl: http://centralidp.tx.test/auth/realms/CX-Central/protocol/openid-connect/token
          client:
            id: satest02
      ingresses:
        - enabled: true
          hostname: "dataprovider-controlplane.tx.test"
          endpoints:
            - default
            - protocol
            - management
          tls:
            enabled: false
    dataplane:
      ingresses:
        - enabled: true
          hostname: "dataprovider-dataplane.tx.test"
          endpoints:
            - default
            - public
          tls:
            enabled: false
  # -- uncomment the following for persistance
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true
  # digital-twin-registry:
  #   postgresql:
  #     primary:
  #       persistence:
  #         enabled: true

dataconsumerTwo:
  enabled: false
  secrets:
    edc-miw-keycloak-secret: tPwy4exxH1sXBRQouobSA2nNVaaPuwCs
  tractusx-connector:
    participant:
      id: BPNL00000003AVTH
    controlplane:
      ssi:
        miw:
          url: http://managed-identity-wallets.tx.test
          authorityId: BPNL00000003CRHK
        oauth:
          tokenurl: http://centralidp.tx.test/auth/realms/CX-Central/protocol/openid-connect/token
          client:
            id: satest03
      endpoints:
        management:
          authKey: TEST3
      ingresses:
        - enabled: true
          hostname: "dataconsumer-2-controlplane.tx.test"
          endpoints:
            - default
            - protocol
            - management
          tls:
            enabled: false
    dataplane:
      ingresses:
        - enabled: true
          hostname: "dataconsumer-2-dataplane.tx.test"
          endpoints:
            - default
            - public
          tls:
            enabled: false
    # -- uncomment the following for persistance
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

pgadmin4:
  enabled: true
  # -- uncomment the following for persistance
  # persistentVolume:
  #   enabled: true
