# #############################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---
name: Test Kyverno Policies

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  get-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: "${{ steps.output-charts.outputs.charts }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          python-version: '3.10'

      # On pull request only get the charts that changed compared to the main brach
      - name: Set up chart-testing
        if: ${{ github.event_name == 'pull_request' }}
        uses: helm/chart-testing-action@v2.4.0

      - name: List changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CHARTS=$(ct list-changed --target-branch main)" >> $GITHUB_ENV

      # On other events than pull request get all charts
      - name: Get all charts
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "CHARTS=$(echo $(find charts -maxdepth 2 -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||'))" >> $GITHUB_ENV

      - name: Output charts
        id: output-charts
        if: ${{ env.CHARTS != '' }}
        run: |
          arr=(`echo $CHARTS`)
          json=$(echo "${arr[@]}" | jq -ncR 'inputs | split(" ")')
          echo "charts=$json" >> $GITHUB_OUTPUT

  kyverno-validate:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.10.1
    needs: [get-charts]
    if: ${{ needs.get-charts.outputs.charts != '' }}
    strategy:
      fail-fast: false
      matrix:
        chart:
          - ${{ fromJson(needs.get-charts.outputs.charts) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Download chart dependencies (recursive)
        shell: bash
        run: hack/helm-dependencies.bash

      - name: Create Helm template
        run: |
            helm template chart-template ${{ matrix.chart }}/ > ${{ matrix.chart }}/chart-template.yaml

      - name: Download Kyverno CLI
        run: |
          curl -sLO https://github.com/kyverno/kyverno/releases/download/${{ env.VERSION }}/kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          tar -xf kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          ${GITHUB_WORKSPACE}/kyverno version          

      - name: Test new resources against existing policies
        run: ${GITHUB_WORKSPACE}/kyverno apply .github/kyverno-policies/require-run-as-nonroot.yaml -r ${{ matrix.chart }}/chart-template.yaml
